package com.spoelt.luckydice.domain.model

/**
 * Data class representing the points a player has in a specific column of a dice poker game.
 *
 * @property columnId The unique ID for the player's column entry. Typically auto-generated by the
 *                    database.
 * @property playerId The ID of the player to whom this column belongs. This is a foreign key
 *                    referencing the PlayerInfoEntity.
 * @property columnNumber The number of the column in which the points are recorded.
 *                        Column numbers typically start from 1 and go up to 3.
 * @property points The points the player has earned in this specific column. Defaults to 0.
 */
data class PlayerColumn(
    val columnId: Long,
    val playerId: Long,
    val columnNumber: Int,
    val points: Int = 0
)